server:
  port: 9191

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/users/**
        - id: POST-SERVICE
          uri: lb://POST-SERVICE
          predicates:
            - Path=/api/posts/**
