server:
  port: 9091

spring:
  application:
    name: USER-SERVICE
eureka:
  client:
    register-with-eureka: true
    fetch-registry: false
    service-url:
      default-url: http://localhost:8761/eureka
    instance:
      hostname: localhost